# Generated by Django 3.1.4 on 2021-01-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tweet_id', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('image_path', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
            ],
        ),
    ]
